cmake_minimum_required(VERSION 3.27)

# 엔진의 OpenGL 관련 설정
set(GL_MAJOR 4)
set(GL_MINOR 6)
set(GL_RED_SIZE 8)
set(GL_GREEN_SIZE 8)
set(GL_BLUE_SIZE 8)
set(GL_ALPHA_SIZE 8)
set(GL_DEPTH_SIZE 24)
set(GL_STENCIL_SIZE 8)
set(GL_DOUBLE_BUFFER 1)
set(GL_MULTISAMPLE_BUFFERS 1)
set(GL_MULTISAMPLE_SAMPLES 16)